apiVersion: v2
name: axetrading-api
description: A Helm chart for Kubernetes
type: application
version: 2.2.4
appVersion: "1.0.0"
dependencies:
  - name: volume-provisioner
    version: 1.0.0
    repository: "file://./charts/volume-provisioner"
    condition: volume-provisioner.enabled
