apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axetrading-api.fullname" . }}
  labels:
    {{- include "axetrading-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "axetrading-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- if .Values.safeToEvict.enabled }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- else }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "axetrading-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "axetrading-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.secretsStore.enabled }}
      - name: {{ include "axetrading-api.fullname" . }}-secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "axetrading-api.fullname" . }}-secrets
      {{- end }}
      {{- if .Values.logFetcher.enabled }}
      - name: {{ include "axetrading-api.fullname" .}}-app-logs
        emptyDir: {}
      {{- end }}
      containers:
        - name: {{ include "axetrading-api.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
           {{- if .Values.secretsStore.enabled }}
            - name: {{ include "axetrading-api.fullname" . }}-secrets-store
              mountPath: /mnt/secrets/
              readOnly: true
           {{- end }}
           {{- if .Values.logFetcher.enabled }}
            - name: {{ include "axetrading-api.fullname" .}}-app-logs
              mountPath: {{ .Values.logFetcher.logsPath }}
           {{- end }}
          ports:
            - name: appport
              containerPort: {{ .Values.service.appport }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.appport }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds}}
            failureThreshold: 3
            periodSeconds: 1
          readinessProbe:
            {{- if .Values.readiness.httpCheck.enabled }}
            httpGet:
              path: "/healthcheck"
              port: {{ .Values.service.appport }}
            {{- end }}
            {{- if .Values.readiness.tpcCheck.enabled }}
            tcpSocket:
              port: {{ .Values.service.appport }}
            {{- end }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.logFetcher.enabled }}
        - name: {{ include "axetrading-api.fullname" . }}-log-fetcher
          image: {{ .Values.logFetcher.image }}
          imagePullPolicy: {{ .Values.logFetcher.imagePullPolicy }}
          env:
            - name: LOGS_PATH
              value: {{ .Values.logFetcher.logsPath }}
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: 100m
              memory: "32Mi"
          volumeMounts:
            - name: {{ include "axetrading-api.fullname" .}}-app-logs
              mountPath: {{ .Values.logFetcher.logsPath }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
