{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "axetrading-api.fullname" . }}-pv
  labels:
      {{- include "axetrading-api.labels" . | nindent 4 }}
  {{- if .Values.persistence.annotations }}
  annotations:
      {{ toYaml .Values.persistence.annotations | indent 10 }}
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
    - lookupcache=pos
    - noatime
    - intr
    - _netdev
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsProvisioner.efsFileSystemId }}
{{- end }}


