{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "axetrading-api.fullname" . }}-rules
  labels:
    {{- include "axetrading-api.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.additionalLabels -}}
{{- toYaml . | nindent 4 -}}
    {{- end }}
spec:
  {{- with .Values.prometheusRule.rules }}
  groups:
    - name: {{ template "axetrading-api.fullname" $ }}
      rules: >
        {{- . | nindent 8 }}
  {{- end }}
{{- end }}