{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "axetrading-api.fullname" . }}-rules
  labels:
    {{- include "axetrading-api.labels" . | nindent 4 }}
spec:
  {{- with .Values.prometheusRule.rules }}
  groups:
    - name: {{ include "axetrading-api.fullname" . }}
      rules: {{ toYaml . | nindent 8 }}
  {{- end }}
{{- end }}