apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "axetrading-api.fullname" . }}
  labels:
  {{- include "axetrading-api.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - jobs
  - deployments
  verbs:
  - create
  - read
  - update