apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "axetrading-api.fullname" . }}
  labels:
  {{- include "axetrading-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "axetrading-api.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "axetrading-api.fullname" . }}
  namespace: '{{ .Release.Namespace }}'