apiVersion: v1
kind: Service
metadata:
  name: {{ include "axetrading-api.fullname" . }}
  labels:
    {{- include "axetrading-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.appport }}
      protocol: TCP
      name: appport
  selector:
    {{- include "axetrading-api.selectorLabels" . | nindent 4 }}
