apiVersion: v1
kind: Service
metadata:
  name: {{ include "axetrading-api.fullname" . }}
  labels:
    {{- include "axetrading-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.appport }}
      protocol: TCP
      name: appport
    {{- if .Values.service.additionalPorts }}
    {{ range .Value.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "axetrading-api.selectorLabels" . | nindent 4 }}
