{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "axetrading-api.fullname". }}
  labels:
    {{- include "axetrading-api.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: {{ .Values.serviceMonitor.port }}
    path: /metrics
    interval: 10s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "axetrading-api.selectorLabels". | nindent 6 }}
{{- end }}
