{{- if .Values.targetGroupBinding.enabled -}}
{{- $fullName := include "axetrading.fullname" . -}}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "axetrading.fullname" . }}
  labels:
    {{- include "axetrading.labels" . | nindent 4 }}
spec:
  serviceRef: 
    name: {{ $fullName }}
    port: {{ .Values.targetGroupBinding.port}}
  targetGroupARN: {{ .Values.targetGroupBinding.targetGroupARN }}
{{- end }}
