{{- if .Values.volumeProvisioner.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.volumeName }}-pvc
  labels:
      {{- include "axetrading-api.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end}}